[2024-12-04T10:54:00.314+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T10:54:00.332+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelada.save_data scheduled__2024-12-04T10:00:00+00:00 [queued]>
[2024-12-04T10:54:00.344+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelada.save_data scheduled__2024-12-04T10:00:00+00:00 [queued]>
[2024-12-04T10:54:00.345+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-12-04T10:54:00.359+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): save_data> on 2024-12-04 10:00:00+00:00
[2024-12-04T10:54:00.371+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=100) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T10:54:00.372+0000] {standard_task_runner.py:72} INFO - Started process 103 to run task
[2024-12-04T10:54:00.373+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_atropelada', 'save_data', 'scheduled__2024-12-04T10:00:00+00:00', '--job-id', '2329', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmpk8_670rz']
[2024-12-04T10:54:00.374+0000] {standard_task_runner.py:105} INFO - Job 2329: Subtask save_data
[2024-12-04T10:54:00.424+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_atropelada.save_data scheduled__2024-12-04T10:00:00+00:00 [running]> on host 7102278bc4c1
[2024-12-04T10:54:00.562+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_atropelada' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-04T10:00:00+00:00'
[2024-12-04T10:54:00.563+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-04T10:54:00.563+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-04T10:54:00.563+0000] {logging_mixin.py:190} INFO - Current task name:save_data state:running start_date:2024-12-04 10:54:00.333101+00:00
[2024-12-04T10:54:00.564+0000] {logging_mixin.py:190} INFO - Dag name:get_inaturalist_data_atropelada and current dag run status:running
[2024-12-04T10:54:00.565+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T10:56:13.400+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7d08d26f0e90>, 'Connection to 192.168.30.21 timed out. (connect timeout=300)')': /environbit?location=
[2024-12-04T10:58:28.967+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7d08d256c9e0>, 'Connection to 192.168.30.21 timed out. (connect timeout=300)')': /environbit?location=
[2024-12-04T11:00:44.536+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7d08d256cc50>, 'Connection to 192.168.30.21 timed out. (connect timeout=300)')': /environbit?location=
[2024-12-04T11:03:00.503+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7d08d256d1c0>, 'Connection to 192.168.30.21 timed out. (connect timeout=300)')': /environbit?location=
[2024-12-04T11:03:00.721+0000] {minio.py:40} INFO - created inaturalist_data/atropelada_data/2024/12/04/atropelada_observations_105357.csv object; etag: ded37d891c043801aa561296e8c6a789, version-id: None
[2024-12-04T11:03:00.721+0000] {minio.py:42} INFO - Data successfully uploaded to MinIO in bucket environbit under inaturalist_data/atropelada_data/2024/12/04/atropelada_observations_105357.csv
[2024-12-04T11:03:00.721+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-04T11:03:00.734+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T11:03:00.735+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=get_inaturalist_data_atropelada, task_id=save_data, run_id=scheduled__2024-12-04T10:00:00+00:00, execution_date=20241204T100000, start_date=20241204T105400, end_date=20241204T110300
[2024-12-04T11:03:00.752+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-04T11:03:00.752+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-04T11:03:00.752+0000] {logging_mixin.py:190} INFO - Dag name:get_inaturalist_data_atropelada queued_at:2024-12-04 10:53:37.329589+00:00
[2024-12-04T11:03:00.753+0000] {logging_mixin.py:190} INFO - Task hostname:7102278bc4c1 operator:_PythonDecoratedOperator
[2024-12-04T11:03:00.792+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-04T11:03:00.815+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-04T11:03:00.818+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
