[2024-11-25T16:31:18.430+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-25T16:31:18.442+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_gbif_data_atropelada.process_data scheduled__2024-11-25T16:00:00+00:00 [queued]>
[2024-11-25T16:31:18.448+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_gbif_data_atropelada.process_data scheduled__2024-11-25T16:00:00+00:00 [queued]>
[2024-11-25T16:31:18.449+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2024-11-25T16:31:18.458+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): process_data> on 2024-11-25 16:00:00+00:00
[2024-11-25T16:31:18.466+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=655) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-25T16:31:18.467+0000] {standard_task_runner.py:72} INFO - Started process 658 to run task
[2024-11-25T16:31:18.468+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_gbif_data_atropelada', 'process_data', 'scheduled__2024-11-25T16:00:00+00:00', '--job-id', '1506', '--raw', '--subdir', 'DAGS_FOLDER/gbif_dag.py', '--cfg-path', '/tmp/tmpyto_cu43']
[2024-11-25T16:31:18.468+0000] {standard_task_runner.py:105} INFO - Job 1506: Subtask process_data
[2024-11-25T16:31:18.503+0000] {task_command.py:467} INFO - Running <TaskInstance: get_gbif_data_atropelada.process_data scheduled__2024-11-25T16:00:00+00:00 [running]> on host 07f92f2579af
[2024-11-25T16:31:18.594+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_gbif_data_atropelada' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T16:00:00+00:00'
[2024-11-25T16:31:18.594+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-25T16:31:18.595+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-25T16:31:18.595+0000] {logging_mixin.py:190} INFO - Current task name:process_data state:running start_date:2024-11-25 16:31:18.443089+00:00
[2024-11-25T16:31:18.595+0000] {logging_mixin.py:190} INFO - Dag name:get_gbif_data_atropelada and current dag run status:running
[2024-11-25T16:31:18.595+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-25T16:31:18.596+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gbif_dag.py", line 260, in process_data
    writer = csv.DictWriter(csvfile, fieldnames=occurrences[0].keys())
                                                ~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-11-25T16:31:18.606+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-25T16:31:18.607+0000] {logging_mixin.py:190} INFO - Task start:2024-11-25 16:31:18.443089+00:00 end:2024-11-25 16:31:18.606441+00:00 duration:0.163352
[2024-11-25T16:31:18.607+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): process_data> dag:<DAG: get_gbif_data_atropelada> dagrun:<DagRun get_gbif_data_atropelada @ 2024-11-25 16:00:00+00:00: scheduled__2024-11-25T16:00:00+00:00, state:running, queued_at: 2024-11-25 16:30:00.584267+00:00. externally triggered: False>
[2024-11-25T16:31:18.607+0000] {logging_mixin.py:190} INFO - Failure caused by list index out of range
[2024-11-25T16:31:18.607+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=get_gbif_data_atropelada, task_id=process_data, run_id=scheduled__2024-11-25T16:00:00+00:00, execution_date=20241125T160000, start_date=20241125T163118, end_date=20241125T163118
[2024-11-25T16:31:18.619+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-25T16:31:18.619+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1506 for task process_data (list index out of range; 658)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gbif_dag.py", line 260, in process_data
    writer = csv.DictWriter(csvfile, fieldnames=occurrences[0].keys())
                                                ~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-11-25T16:31:18.640+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-25T16:31:18.659+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-25T16:31:18.660+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
